### ISSUE TITLE
Output messages of kafka-cscout miss some fields

### ISSUE THREAD

**Issue by MagielBruntink** [fasten-project/debian-builder#2]
Dear @StefanosChaliasos,

As discussed in the dev call, we are missing some fields in the output messages of Cscout. The current messages look like the following:
```
{
   "plugin_name": "CScoutKafkaPlugin",
   "plugin_version": "0.0.1",
   "input": {
      "package": "anna",
      "version": "1.71",
      "arch": "amd64",
      "release": "buster",
      "source": "anna",
      "source_version": "1.71",
      "date": ""
   },
   "created_at": "1613034333.396401",
   "payload": {
      "dir": "/mnt/fasten/c/callgraphs/a/anna/buster/1.71/amd64/file.json"
   }
}
```
Could you please consider adding the "forge" and "sourcePath" fields to the payload, to make the life of the downstream plugins easier :-) eg. as follows:
```
   "payload": {
      "forge" : "debian",
      "sourcePath" : "/mnt/fasten/c/sources/a/anna/buster/1.71/amd64"
      "dir": "/mnt/fasten/c/callgraphs/a/anna/buster/1.71/amd64/file.json"
   }
```
Here the `/mnt/fasten/c` is the path provided to the Cscout plugin with the -d command line parameter.

**Comment by StefanosChaliasos** [comment]
Hello, sorry for the late response. I added the two fields you requested, and I updated the docker image (sha256:162d1fbe8c3c6cfb321cdb349319a880f4cb1df53f2c9e0848810a624bd4d980). Thanks for the report!

**Comment by StefanosChaliasos** [comment]
You can also use `docker.pkg.github.com/fasten-project/debian-builder/kafka-cscout:1.0.1`.

**Comment by MagielBruntink** [comment]
Dear Stefanos, thank you very much for making the change and updating the image. I have been incomplete, however :-( We need two additional fields in the payload, being product and version (https://github.com/fasten-project/fasten/wiki/Revision-Call-Graph-format#c) otherwise our plugin cannot identify for where to insert the quality metadata. Would it be possible please to add those fields also?
```
   "payload": {
      "forge" : "debian",
      "product" : "anna",
      "version" : "1.71",
      "sourcePath" : "/mnt/fasten/c/sources/a/anna/buster/1.71/amd64",
      "dir": "/mnt/fasten/c/callgraphs/a/anna/buster/1.71/amd64/file.json"
   }
```

**Comment by MagielBruntink** [comment]
> You can also use `docker.pkg.github.com/fasten-project/debian-builder/kafka-cscout:1.0.1`.

We'll use that image in the future :-) Thanks!

**Comment by StefanosChaliasos** [comment]
Done. I updated both images. I also added architecture (`arch` field). It may be useful for other plugins or in the future if we add support for multiple architectures.

dockerhub: `sha256:803df614ee12a5d438c3936b24154b0c45b57c911d404f085bb7afaf21337bca`
github: `docker.pkg.github.com/fasten-project/debian-builder/kafka-cscout:1.0.2`

**Comment by MagielBruntink** [comment]
Hey Stefanos, thanks again! As we get further, I'm unfortunately discovering another issue, which is mostly due to my earlier request. It seems the directory structures for the downloaded sources and where the call graphs are stored are not the same. For example, on disk the structures look like:
```
/mnt/fasten/sources/a/anna/1.71
/mnt/fasten/callgraphs/a/anna/buster/1.71/amd64
```
By my request the sourcePath field in the Kafka message now look as follows, which is unfortunately not correct:
```
"sourcePath" : "/mnt/fasten/sources/a/anna/buster/1.71/amd64"
```
I did assume the sourcePath should also include the release and arch information, but it seems the Cscout plugin does not put those into the path for downloaded sources. What do you think is it the best solution here? Let me know how if I can help resolve this.

**Comment by StefanosChaliasos** [comment]
Thanks for pointing this out. We save the sources to directories without the architecture and the distribution because the source code is the same. I removed them from `sourcePath`. I updated both images. Probably, it's more convenient to use the Github images (`docker.pkg.github.com/fasten-project/debian-builder/kafka-cscout:1.0.3`).

**Comment by MagielBruntink** [comment]
I ran the C pipeline with the the latest and everything works out, including the REST API :-)

![image](https://user-images.githubusercontent.com/3635696/108527467-99904680-72d2-11eb-8b4c-3039fb1811dd.png)
